export const DUA_CATEGORIES = [
    { key: 'general', title: 'General', arabic: 'عام' },
    { key: 'morning_evening', title: 'Morning & Evening', arabic: 'أذكار الصباح والمساء' },
    { key: 'after_salah', title: 'After Salah', arabic: 'بعد الصلاة' },
    { key: 'before_sleep', title: 'Before Sleep', arabic: 'قبل النوم' },
    { key: 'waking_up', title: 'Waking Up', arabic: 'عند الاستيقاظ' },
    { key: 'entering_leaving_home', title: 'Home', arabic: 'دخول وخروج المنزل' },
    { key: 'mosque', title: 'Mosque', arabic: 'المسجد' },
    { key: 'eating_drinking', title: 'Food & Drink', arabic: 'الطعام والشراب' },
    { key: 'travel', title: 'Travel', arabic: 'السفر' },
    { key: 'distress_anxiety', title: 'Distress & Anxiety', arabic: 'الهم والقلق' },
    { key: 'forgiveness', title: 'Forgiveness', arabic: 'الاستغفار' },
    { key: 'gratitude', title: 'Gratitude', arabic: 'الشكر' },
    { key: 'protection', title: 'Protection', arabic: 'الحماية' },
    { key: 'health_healing', title: 'Healing', arabic: 'الشفاء' },
    { key: 'rain', title: 'Rain', arabic: 'المطر' },
    { key: 'death_grave', title: 'Death & Grave', arabic: 'الموت والقبر' },
    { key: 'knowledge', title: 'Knowledge', arabic: 'العلم' },
    { key: 'rizq_sustenance', title: 'Sustenance', arabic: 'الرزق' },
    { key: 'family', title: 'Family', arabic: 'الأسرة' },
    { key: 'marriage', title: 'Marriage', arabic: 'الزواج' },
    { key: 'children', title: 'Children', arabic: 'الأولاد' },
    { key: 'repentance', title: 'Repentance', arabic: 'التوبة' },
    { key: 'guidance', title: 'Guidance', arabic: 'الهداية' },
    { key: 'patience', title: 'Patience', arabic: 'الصبر' },
    { key: 'fear', title: 'Fear', arabic: 'الخوف' },
    { key: 'hope', title: 'Hope', arabic: 'الرجاء' },
    { key: 'love_of_allah', title: 'Love of Allah', arabic: 'محبة الله' },
    { key: 'dhikr', title: 'Dhikr', arabic: 'الذكر' },
];